2025-03-23 03:19:41,405 DEBUG    root            Loaded Command Group: ['gcloud', 'run']
2025-03-23 03:19:41,465 DEBUG    root            Loaded Command Group: ['gcloud', 'run', 'deploy']
2025-03-23 03:19:41,469 DEBUG    root            Running [gcloud.run.deploy] with arguments: [--allow-unauthenticated: "True", --image: "europe-docker.pkg.dev/mywebproject-420221/mywebsite/myserver:lastest", --max-instances: "<googlecloudsdk.command_lib.run.flags.ScaleValue object at 0x1062faad0>", --region: "europe-west1", SERVICE: "myweb"]
2025-03-23 03:19:41,479 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): serviceusage.googleapis.com:443
2025-03-23 03:19:42,354 DEBUG    urllib3.connectionpool https://serviceusage.googleapis.com:443 "GET /v1/projects/mywebproject-420221/services/run.googleapis.com?alt=json HTTP/11" 403 None
2025-03-23 03:19:42,377 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): europe-west1-run.googleapis.com:443
2025-03-23 03:19:42,756 DEBUG    urllib3.connectionpool https://europe-west1-run.googleapis.com:443 "GET /apis/serving.knative.dev/v1/namespaces/mywebproject-420221/services/myweb?alt=json HTTP/11" 403 None
2025-03-23 03:19:42,758 DEBUG    root            (gcloud.run.deploy) PERMISSION_DENIED: Permission 'run.services.get' denied on resource 'namespaces/mywebproject-420221/services/myweb' (or resource may not exist). This command is authenticated as weitingchen0502@gmail.com which is the active account specified by the [core/account] property.
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/google-cloud-sdk/515.0.0/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 981, in Execute
    resources = calliope_command.Run(cli=self, args=args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/google-cloud-sdk/515.0.0/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 934, in Run
    resources = command_instance.Run(args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/google-cloud-sdk/515.0.0/google-cloud-sdk/lib/surface/run/deploy.py", line 713, in Run
    service = operations.GetService(service_ref)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/google-cloud-sdk/515.0.0/google-cloud-sdk/lib/googlecloudsdk/command_lib/run/serverless_operations.py", line 335, in GetService
    service_get_response = self._client.namespaces_services.Get(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/google-cloud-sdk/515.0.0/google-cloud-sdk/lib/googlecloudsdk/generated_clients/apis/run/v1/run_v1_client.py", line 802, in Get
    return self._RunMethod(
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/google-cloud-sdk/515.0.0/google-cloud-sdk/lib/third_party/apitools/base/py/base_api.py", line 747, in _RunMethod
    return self.ProcessHttpResponse(method_config, http_response, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/google-cloud-sdk/515.0.0/google-cloud-sdk/lib/third_party/apitools/base/py/base_api.py", line 753, in ProcessHttpResponse
    self.__ProcessHttpResponse(method_config, http_response, request))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/google-cloud-sdk/515.0.0/google-cloud-sdk/lib/third_party/apitools/base/py/base_api.py", line 612, in __ProcessHttpResponse
    raise exceptions.HttpError.FromResponse(
apitools.base.py.exceptions.HttpForbiddenError: HttpError accessing <https://europe-west1-run.googleapis.com/apis/serving.knative.dev/v1/namespaces/mywebproject-420221/services/myweb?alt=json>: response: <{'vary': 'Origin, X-Origin, Referer', 'content-type': 'application/json; charset=UTF-8', 'content-encoding': 'gzip', 'date': 'Sun, 23 Mar 2025 02:19:42 GMT', 'server': 'ESF', 'x-xss-protection': '0', 'x-frame-options': 'SAMEORIGIN', 'x-content-type-options': 'nosniff', 'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000', 'transfer-encoding': 'chunked', 'status': 403}>, content <{
  "error": {
    "code": 403,
    "message": "Permission 'run.services.get' denied on resource 'namespaces/mywebproject-420221/services/myweb' (or resource may not exist).",
    "status": "PERMISSION_DENIED"
  }
}
>
2025-03-23 03:19:42,760 ERROR    root            (gcloud.run.deploy) PERMISSION_DENIED: Permission 'run.services.get' denied on resource 'namespaces/mywebproject-420221/services/myweb' (or resource may not exist). This command is authenticated as weitingchen0502@gmail.com which is the active account specified by the [core/account] property.
